#!/usr/bin/env python3
"""
Body Advice Blog — Daily Article Generator
SEO-optimized for 2026. Targets real search queries.
NO medical claims — cosmetic product mentions only.
Topics generated by AI — never repeats.
Includes: fake warning, cream combination tip, FAQ, Schema.org
"""

import os, json, datetime, re, sys
import urllib.request, urllib.error

API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
MODEL   = "claude-sonnet-4-6"
DOMAIN  = "https://www.bodyadvice.site"

PLATFORMS = [
    "artrovex.shop (official store)",
    "Amazon",
    "Etsy",
    "Allegro",
    "TikTok Shop",
    "eBay",
]

LANGS = ["en", "de", "it", "es", "fr"]

LANG_NAMES = {
    "en": "English",
    "de": "German",
    "it": "Italian",
    "es": "Spanish",
    "fr": "French",
}

FAKE_WARNING = {
    "en": {
        "heading": "⚠️ Warning: Counterfeit products exist — buy only from official sources",
        "text": "Over the years, health authorities including Austria's BASG (2019) and Colombia's INVIMA (2020) issued warnings about counterfeit and fraudulently marketed joint creams sold under similar names by unauthorized distributors. These warnings were specifically about fake products — not about the original Artrovex or Hondrocream. We actively fight counterfeiting. To be safe, only purchase from verified platforms: <strong>artrovex.shop</strong> (official), <strong>Amazon</strong>, <strong>Etsy</strong>, <strong>TikTok Shop</strong>, <strong>eBay</strong>, or <strong>Allegro</strong>. If the price seems too good or the packaging looks different — it's probably a fake."
    },
    "de": {
        "heading": "⚠️ Warnung: Fälschungen im Umlauf — kaufen Sie nur bei offiziellen Quellen",
        "text": "In den vergangenen Jahren haben Gesundheitsbehörden, darunter die österreichische BASG (2019) und Kolumbiens INVIMA (2020), Warnungen vor gefälschten und illegal vermarkteten Gelenkcremes unter ähnlichen Namen herausgegeben. Diese Warnungen bezogen sich ausdrücklich auf Fälschungen — nicht auf die originalen Produkte Artrovex oder Hondrocream. Wir kämpfen aktiv gegen Fälschungen. Kaufen Sie nur bei verifizierten Plattformen: <strong>artrovex.shop</strong> (offiziell), <strong>Amazon</strong>, <strong>Etsy</strong>, <strong>TikTok Shop</strong>, <strong>eBay</strong> oder <strong>Allegro</strong>."
    },
    "it": {
        "heading": "⚠️ Attenzione: esistono prodotti contraffatti — acquistate solo da fonti ufficiali",
        "text": "Negli anni passati, autorità sanitarie tra cui il BASG austriaco (2019) e l'INVIMA colombiano (2020) hanno emesso avvisi riguardo a creme articolari contraffatte e commercializzate illegalmente con nomi simili da distributori non autorizzati. Questi avvisi riguardavano specificamente i falsi — non i prodotti originali Artrovex o Hondrocream. Combattiamo attivamente la contraffazione. Acquistate solo da piattaforme verificate: <strong>artrovex.shop</strong> (ufficiale), <strong>Amazon</strong>, <strong>Etsy</strong>, <strong>TikTok Shop</strong>, <strong>eBay</strong> o <strong>Allegro</strong>."
    },
    "es": {
        "heading": "⚠️ Advertencia: existen productos falsificados — compre solo en fuentes oficiales",
        "text": "En los últimos años, autoridades sanitarias como el BASG austriaco (2019) y el INVIMA colombiano (2020) emitieron alertas sobre cremas articulares falsificadas y comercializadas ilegalmente con nombres similares por distribuidores no autorizados. Estas alertas se referían específicamente a productos falsos — no a los productos originales Artrovex o Hondrocream. Luchamos activamente contra la falsificación. Compre solo en plataformas verificadas: <strong>artrovex.shop</strong> (oficial), <strong>Amazon</strong>, <strong>Etsy</strong>, <strong>TikTok Shop</strong>, <strong>eBay</strong> o <strong>Allegro</strong>."
    },
    "fr": {
        "heading": "⚠️ Attention : des contrefaçons existent — achetez uniquement auprès de sources officielles",
        "text": "Ces dernières années, des autorités sanitaires dont le BASG autrichien (2019) et l'INVIMA colombien (2020) ont émis des mises en garde concernant des crèmes articulaires contrefaites et commercialisées illégalement sous des noms similaires par des distributeurs non autorisés. Ces avertissements concernaient spécifiquement les faux produits — pas les produits originaux Artrovex ou Hondrocream. Nous luttons activement contre la contrefaçon. N'achetez que sur des plateformes vérifiées : <strong>artrovex.shop</strong> (officiel), <strong>Amazon</strong>, <strong>Etsy</strong>, <strong>TikTok Shop</strong>, <strong>eBay</strong> ou <strong>Allegro</strong>."
    },
}

COMBO_TIP = {
    "en": "Many people find it beneficial to use both Artrovex and Hondrocream as part of their massage routine — Artrovex first (cooling then warming), followed by Hondrocream (immediate warmth) after 10–15 minutes. The combination provides a layered sensation that many users enjoy as part of their wellness ritual.",
    "de": "Viele Menschen finden es vorteilhaft, sowohl Artrovex als auch Hondrocream als Teil ihrer Massageroutine zu verwenden — zuerst Artrovex (kühlend, dann wärmend), gefolgt von Hondrocream (sofortige Wärme) nach 10–15 Minuten. Die Kombination bietet ein abgestuftes Gefühl, das viele Anwender als Teil ihres Wellness-Rituals schätzen.",
    "it": "Molte persone trovano vantaggioso usare sia Artrovex che Hondrocream come parte della loro routine di massaggio — prima Artrovex (rinfrescante poi riscaldante), seguito da Hondrocream (calore immediato) dopo 10–15 minuti. La combinazione offre una sensazione stratificata che molti utenti apprezzano come parte del loro rituale di benessere.",
    "es": "Muchas personas encuentran beneficioso usar tanto Artrovex como Hondrocream como parte de su rutina de masaje — primero Artrovex (refrescante luego calentador), seguido de Hondrocream (calor inmediato) después de 10-15 minutos. La combinación proporciona una sensación en capas que muchos usuarios disfrutan como parte de su ritual de bienestar.",
    "fr": "Beaucoup de personnes trouvent bénéfique d'utiliser à la fois Artrovex et Hondrocream dans le cadre de leur routine de massage — d'abord Artrovex (refroidissant puis chauffant), suivi de Hondrocream (chaleur immédiate) après 10-15 minutes. La combinaison offre une sensation en couches que de nombreux utilisateurs apprécient dans le cadre de leur rituel bien-être.",
}

def get_platform_for_today():
    day = (datetime.date.today() - datetime.date(2024, 1, 1)).days
    return PLATFORMS[day % len(PLATFORMS)]

def get_cream_for_today():
    day = (datetime.date.today() - datetime.date(2024, 1, 1)).days
    if day % 2 == 0:
        return "Artrovex cream (dual-effect massage cream: starts with a cooling sensation, then transitions into a gentle warming effect — two distinct phases)"
    else:
        return "Hondrocream (warming massage cream: delivers immediate, direct warmth from the very first application — no cooling phase)"

def call_claude(prompt):
    payload = json.dumps({
        "model": MODEL,
        "max_tokens": 2000,
        "messages": [{"role": "user", "content": prompt}]
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=payload,
        headers={
            "Content-Type": "application/json",
            "x-api-key": API_KEY,
            "anthropic-version": "2023-06-01",
        },
        method="POST"
    )
    with urllib.request.urlopen(req) as r:
        data = json.loads(r.read())
    return data["content"][0]["text"]

def get_unique_topic(used_topics):
    used_list = "\n".join(f"- {t}" for t in used_topics[-60:]) if used_topics else "None yet"
    prompt = f"""You are a wellness blog editor. Generate ONE unique blog topic about joints, muscles, massage, or body movement.

RULES:
- Must be specific and practical
- Must NOT be similar to any topic already used
- 5-10 words maximum
- In English
- No medical claims

Already used topics (do NOT repeat):
{used_list}

Respond with ONLY the topic text, nothing else."""
    raw = call_claude(prompt).strip()
    raw = re.sub(r'^["\'"]|["\'"]$', '', raw)
    return raw

def generate_article(topic, platform, lang, cream_of_day):
    lang_name = LANG_NAMES[lang]
    prompt = f"""You are a professional SEO wellness blog writer for 2026. Write a high-quality, Google-optimized wellness article in {lang_name}.

TOPIC: {topic}
TARGET CREAM: {cream_of_day}
PLATFORM TO MENTION: {platform}

STRICT RULES:
1. Write ENTIRELY in {lang_name}.
2. NO medical claims. No "treats", "heals", "cures", "relieves pain", "therapeutic", "medicinal".
3. Mention {cream_of_day} naturally as a cosmetic massage product — part of wellness routine only.
4. Include double application tip: apply cream, massage 2-3 min, wait 10 min, apply second layer.
5. Include handwashing reminder.
6. Write like a real person — warm, direct, honest. Not AI-sounding.
7. Include 3 FAQ questions and answers relevant to the topic (for Google rich results).
8. Use SEO-friendly subheadings that people actually search for.
9. Naturally mention {platform} as a place to find the cream.

RESPOND WITH VALID JSON ONLY. No markdown, no backticks:
{{
  "title": "SEO-optimized engaging title with the cream name naturally included",
  "meta_description": "155 char SEO meta description",
  "intro": "2-3 sentence personal hook",
  "sections": [
    {{"heading": "heading people search for", "text": "detailed helpful text"}},
    {{"heading": "heading people search for", "text": "detailed helpful text"}},
    {{"heading": "heading people search for", "text": "detailed helpful text"}}
  ],
  "product_mention": "natural cream mention as massage wellness product",
  "double_tip": "double application tip",
  "wash_reminder": "handwashing reminder",
  "faq": [
    {{"q": "question", "a": "answer"}},
    {{"q": "question", "a": "answer"}},
    {{"q": "question", "a": "answer"}}
  ],
  "cta": "closing motivational line"
}}"""
    raw = call_claude(prompt)
    raw = re.sub(r'^```[a-z]*\n?', '', raw.strip())
    raw = re.sub(r'\n?```$', '', raw.strip())
    return json.loads(raw)

def slugify(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s-]', '', text)
    text = re.sub(r'\s+', '-', text.strip())
    return text[:60]

def build_article_html(data, lang, topic, date_str, slug, cream_of_day):
    sections_html = ""
    for s in data.get("sections", []):
        sections_html += f"""
        <div class="art-sec">
          <h2>{s['heading']}</h2>
          <p>{s['text']}</p>
        </div>"""

    faq_html = ""
    faq_schema = []
    for faq in data.get("faq", []):
        faq_html += f"""
        <div class="faq-item">
          <h3 class="faq-q">{faq['q']}</h3>
          <p class="faq-a">{faq['a']}</p>
        </div>"""
        faq_schema.append({"@type": "Question", "name": faq['q'], "acceptedAnswer": {"@type": "Answer", "text": faq['a']}})

    fake_warn = FAKE_WARNING.get(lang, FAKE_WARNING["en"])
    combo = COMBO_TIP.get(lang, COMBO_TIP["en"])

    cream_name = "Artrovex" if "Artrovex" in cream_of_day else "Hondrocream"

    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Article",
                "headline": data['title'],
                "description": data.get('meta_description', data['intro'][:155]),
                "datePublished": datetime.date.today().isoformat(),
                "author": {"@type": "Organization", "name": "Body Advice"},
                "publisher": {"@type": "Organization", "name": "Body Advice", "url": DOMAIN},
                "inLanguage": lang,
                "url": f"{DOMAIN}/articles/{slug}-{lang}.html"
            },
            {
                "@type": "FAQPage",
                "mainEntity": faq_schema
            }
        ]
    }

    return f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{data['title']}</title>
<meta name="description" content="{data.get('meta_description', data['intro'][:155])}">
<meta name="keywords" content="{cream_name}, {cream_name} original, {cream_name} kaufen, {topic.lower()}, wellness massage cream, joint muscle care">
<meta property="og:title" content="{data['title']}">
<meta property="og:description" content="{data.get('meta_description', data['intro'][:155])}">
<meta property="og:type" content="article">
<meta property="og:url" content="{DOMAIN}/articles/{slug}-{lang}.html">
<link rel="canonical" href="{DOMAIN}/articles/{slug}-{lang}.html">
<script type="application/ld+json">{json.dumps(schema, ensure_ascii=False)}</script>
<link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400&family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Inter',sans-serif;background:#faf8f3;color:#1c1c1c;line-height:1.7;font-size:16px}}
nav{{background:#183d2f;padding:14px 20px;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:100}}
.nb{{font-family:'Lora',serif;color:#52c48a;font-size:17px;text-decoration:none}}
.ns{{background:#52c48a;color:#183d2f;padding:7px 14px;border-radius:6px;font-size:13px;font-weight:700;text-decoration:none}}
.wrap{{max-width:740px;margin:0 auto;padding:32px 18px 60px}}
.date{{font-size:12px;color:#888;letter-spacing:1px;text-transform:uppercase;margin-bottom:14px}}
h1{{font-family:'Lora',serif;font-size:clamp(22px,4vw,32px);line-height:1.25;color:#183d2f;margin-bottom:18px}}
h2{{font-size:18px;font-weight:700;color:#183d2f;margin:24px 0 8px}}
h3{{font-size:15px;font-weight:600;color:#1c1c1c;margin:0 0 6px}}
.lead{{font-size:16px;line-height:1.85;border-left:3px solid #52c48a;padding-left:16px;margin-bottom:28px;font-weight:300;color:#2a2a2a}}
.art-sec{{margin-bottom:22px}}
.art-sec p{{font-size:15px;line-height:1.78;color:#3a3a3a}}
.prod-box{{border-radius:10px;padding:16px 18px;margin:26px 0 16px;font-size:14px;line-height:1.7;background:#eef6ff;border:1px solid #b3d4f0}}
.prod-box h3{{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:#1a6699;margin-bottom:8px}}
.combo-box{{border-radius:10px;padding:16px 18px;margin:16px 0;font-size:14px;line-height:1.7;background:#f0faf5;border:1px solid #b7e4c7;color:#183d2f}}
.combo-box h3{{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:#183d2f;margin-bottom:8px}}
.fake-warning{{border-radius:10px;padding:16px 18px;margin:24px 0;font-size:14px;line-height:1.7;background:#fff8e1;border:2px solid #ffc107}}
.fake-warning h3{{font-size:13px;font-weight:700;color:#e65100;margin-bottom:8px}}
.fake-warning p{{color:#3a3a3a}}
.tip-box{{background:#f2f7f4;border:1px solid #c8e0d2;border-radius:8px;padding:13px 15px;margin:12px 0;font-size:14px;color:#183d2f;line-height:1.65}}
.tip-box strong{{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.5px;color:#2d7d5a;margin-bottom:5px}}
.faq-section{{margin:28px 0}}
.faq-section h2{{font-size:18px;color:#183d2f;margin-bottom:16px}}
.faq-item{{background:white;border-radius:8px;padding:14px 16px;margin-bottom:10px;border:1px solid #e0e8e3}}
.faq-q{{font-size:14px;font-weight:600;color:#183d2f;margin-bottom:6px}}
.faq-a{{font-size:14px;color:#555;line-height:1.6}}
.cta{{background:#183d2f;color:#52c48a;border-radius:8px;padding:14px;text-align:center;font-weight:700;font-size:15px;margin:20px 0 14px}}
.back{{display:inline-block;color:#2d7d5a;font-size:14px;text-decoration:none;margin-bottom:24px}}
.disc{{font-size:11px;color:#999;border-top:1px solid #e5e0d5;padding-top:16px;margin-top:32px;line-height:1.6}}
footer{{background:#183d2f;color:rgba(255,255,255,.4);text-align:center;padding:18px;font-size:12px}}
footer a{{color:#52c48a;text-decoration:none}}
</style>
</head>
<body>
<nav>
  <a class="nb" href="../index.html">🌿 Body Advice</a>
  <a class="ns" href="https://www.artrovex.shop" target="_blank">🛍 Shop</a>
</nav>
<div class="wrap">
  <a class="back" href="../index.html">← All articles</a>
  <div class="date">{date_str} · Wellness Guide</div>
  <h1>{data['title']}</h1>
  <p class="lead">{data['intro']}</p>
  {sections_html}
  <div class="prod-box">
    <h3>💆 Massage & Wellness</h3>
    <p>{data['product_mention']} Available at <a href="https://www.artrovex.shop" target="_blank">artrovex.shop</a>.</p>
  </div>
  <div class="combo-box">
    <h3>💡 Artrovex + Hondrocream together</h3>
    <p>{combo}</p>
  </div>
  <div class="tip-box"><strong>💡 Pro tip — double application</strong>{data['double_tip']}</div>
  <div class="tip-box"><strong>🧼 Important</strong>{data['wash_reminder']}</div>
  <div class="fake-warning">
    <h3>{fake_warn['heading']}</h3>
    <p>{fake_warn['text']}</p>
  </div>
  <div class="faq-section">
    <h2>Frequently Asked Questions</h2>
    {faq_html}
  </div>
  <div class="cta">{data['cta']}</div>
  <p class="disc"><strong>Disclaimer:</strong> This article is for general wellness and informational purposes only. It does not constitute medical advice and is not intended to diagnose, treat, cure, or prevent any condition. Products mentioned are cosmetic items. Always consult a qualified healthcare professional for medical concerns.</p>
</div>
<footer><a href="{DOMAIN}">bodyadvice.site</a> · Wellness & Movement Blog</footer>
</body>
</html>"""

def update_index(articles_meta):
    cards_html = ""
    for m in sorted(articles_meta, key=lambda x: x["date"], reverse=True)[:120]:
        cards_html += f"""
    <div class="card" onclick="location.href='articles/{m['slug']}-{m['lang']}.html'">
      <div class="card-stripe"></div>
      <div class="card-body">
        <div class="card-tag">{m['date']} · {m['lang'].upper()}</div>
        <div class="card-title">{m['title']}</div>
        <div class="card-topic">{m['topic']}</div>
      </div>
    </div>"""

    schema_org = json.dumps({
        "@context": "https://schema.org",
        "@type": "Blog",
        "name": "Body Advice — Wellness Blog",
        "url": DOMAIN,
        "description": "Daily expert tips on joint mobility, muscle care and massage. Updated every day in 5 languages.",
        "inLanguage": ["en", "de", "it", "es", "fr"]
    }, ensure_ascii=False)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Body Advice | Joint & Muscle Wellness Blog — Daily Tips in 5 Languages</title>
<meta name="description" content="Expert daily tips on joint care, muscle recovery, massage techniques and wellness routines. Artrovex and Hondrocream massage cream guides. Updated every day in EN, DE, IT, ES, FR.">
<meta name="keywords" content="Artrovex cream, Hondrocream, joint wellness, muscle massage, knee care, back pain relief, warming cream, cooling cream, massage routine">
<link rel="canonical" href="{DOMAIN}">
<script type="application/ld+json">{schema_org}</script>
<link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400&family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Inter',sans-serif;background:#faf8f3;color:#1c1c1c}}
nav{{background:#183d2f;height:56px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;position:sticky;top:0;z-index:100}}
.nb{{font-family:'Lora',serif;color:#52c48a;font-size:17px;text-decoration:none}}
.ns{{background:#52c48a;color:#183d2f;padding:7px 13px;border-radius:6px;font-size:13px;font-weight:700;text-decoration:none}}
.hero{{background:linear-gradient(150deg,#183d2f,#1e5c40);padding:48px 20px 40px;text-align:center;color:#fff}}
.hero h1{{font-family:'Lora',serif;font-size:clamp(22px,5vw,40px);font-weight:400;margin-bottom:12px}}
.hero h1 em{{color:#52c48a;font-style:italic}}
.hero p{{color:rgba(255,255,255,.65);font-size:15px;max-width:520px;margin:0 auto 22px}}
.hero a{{background:#52c48a;color:#183d2f;padding:11px 24px;border-radius:7px;font-weight:700;font-size:14px;text-decoration:none}}
.wrap{{max-width:960px;margin:0 auto;padding:0 16px 50px}}
.sec-title{{font-family:'Lora',serif;font-size:20px;font-weight:400;color:#183d2f;margin:32px 0 16px;border-bottom:1px solid #e0e8e3;padding-bottom:10px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px}}
.card{{background:#fff;border-radius:10px;overflow:hidden;cursor:pointer;transition:transform .15s;border:1.5px solid #e0e8e3;box-shadow:0 1px 6px rgba(0,0,0,.06)}}
.card:hover{{transform:translateY(-2px);box-shadow:0 4px 16px rgba(0,0,0,.1)}}
.card-stripe{{height:4px;background:linear-gradient(90deg,#183d2f,#52c48a)}}
.card-body{{padding:14px}}
.card-tag{{font-size:10px;color:#2d7d5a;letter-spacing:1.5px;text-transform:uppercase;font-weight:600;margin-bottom:5px}}
.card-title{{font-family:'Lora',serif;font-size:14px;line-height:1.4;color:#1c1c1c}}
.card-topic{{font-size:11px;color:#888;margin-top:6px}}
.trust-bar{{background:#fff8e1;border-top:2px solid #ffc107;border-bottom:2px solid #ffc107;padding:14px 20px;text-align:center;font-size:13px;color:#5a3e00}}
footer{{background:#183d2f;color:rgba(255,255,255,.4);text-align:center;padding:20px;font-size:12px}}
footer a{{color:#52c48a;text-decoration:none}}
</style>
</head>
<body>
<nav>
  <a class="nb" href="#">🌿 Body Advice</a>
  <a class="ns" href="https://www.artrovex.shop" target="_blank">🛍 Shop</a>
</nav>
<div class="hero">
  <h1>Move better.<br><em>Feel better.</em> Live fully.</h1>
  <p>Daily expert tips on joint care, muscle recovery and massage — featuring Artrovex & Hondrocream guides. Updated every day in 5 languages.</p>
  <a href="https://www.artrovex.shop" target="_blank">Discover original Artrovex & Hondrocream →</a>
</div>
<div class="trust-bar">
  ⚠️ <strong>Buy only originals:</strong> Artrovex & Hondrocream are available on <strong>artrovex.shop</strong>, <strong>Amazon</strong>, <strong>Etsy</strong>, <strong>TikTok Shop</strong>, <strong>eBay</strong> and <strong>Allegro</strong>. Counterfeits exist — always verify the source.
</div>
<div class="wrap">
  <div class="sec-title">Latest Articles</div>
  <div class="grid">{cards_html}</div>
</div>
<footer><a href="{DOMAIN}">bodyadvice.site</a> · Wellness & Movement Blog · Updated daily · EN DE IT ES FR</footer>
</body>
</html>"""

    os.makedirs("docs", exist_ok=True)
    with open("docs/index.html", "w", encoding="utf-8") as f:
        f.write(html)
    print(f"✅ Index updated with {len(articles_meta)} articles")

def generate_sitemap(articles_meta):
    today = datetime.date.today().isoformat()
    urls = f"""  <url>
    <loc>{DOMAIN}/</loc>
    <lastmod>{today}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>"""
    for m in articles_meta:
        urls += f"""
  <url>
    <loc>{DOMAIN}/articles/{m['slug']}-{m['lang']}.html</loc>
    <lastmod>{m['date']}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>"""
    sitemap = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{urls}
</urlset>"""
    with open("docs/sitemap.xml", "w", encoding="utf-8") as f:
        f.write(sitemap)
    with open("docs/robots.txt", "w", encoding="utf-8") as f:
        f.write(f"User-agent: *\nAllow: /\n\nSitemap: {DOMAIN}/sitemap.xml")
    print("✅ sitemap.xml and robots.txt generated")

def main():
    if not API_KEY:
        print("❌ ANTHROPIC_API_KEY not set")
        sys.exit(1)

    platform = get_platform_for_today()
    cream_of_day = get_cream_for_today()
    date_str = datetime.date.today().strftime("%B %d, %Y")

    meta_path = "docs/articles_meta.json"
    os.makedirs("docs/articles", exist_ok=True)

    if os.path.exists(meta_path):
        with open(meta_path, "r") as f:
            articles_meta = json.load(f)
    else:
        articles_meta = []

    used_topics = list(set(m["topic"] for m in articles_meta))

    print("🧠 Generating unique topic...")
    topic = get_unique_topic(used_topics)
    slug = slugify(topic)

    print(f"📝 Topic: {topic}")
    print(f"🛍 Platform: {platform}")
    print(f"🧴 Cream: {cream_of_day[:50]}...")

    for lang in LANGS:
        print(f"  🌐 Generating {lang.upper()}...")
        try:
            data = generate_article(topic, platform, lang, cream_of_day)
            html = build_article_html(data, lang, topic, date_str, slug, cream_of_day)
            path = f"docs/articles/{slug}-{lang}.html"
            with open(path, "w", encoding="utf-8") as f:
                f.write(html)
            articles_meta.append({
                "date": datetime.date.today().isoformat(),
                "lang": lang,
                "slug": slug,
                "title": data["title"],
                "topic": topic,
                "file": f"articles/{slug}-{lang}.html"
            })
            print(f"  ✅ {lang.upper()} saved")
        except Exception as e:
            print(f"  ❌ {lang.upper()} failed: {e}")

    with open(meta_path, "w") as f:
        json.dump(articles_meta, f, indent=2)

    update_index(articles_meta)
    generate_sitemap(articles_meta)
    print("🎉 Done!")

if __name__ == "__main__":
    main()
